const EtherWallet = artifacts.require('EtherWallet')

// "accounts" are the accounts generated by ganache
module.exports = function(deployer, _network, accounts) {
  const owner = accounts[0]
  deployer.deploy(EtherWallet, owner)
}

